#!/usr/bin/env python3
"""Cross-tabulate the normalized census and derive the corpus worklist.

Reads analysis/manuscript-census-2026-09-14/census-normalized.json. Writes
analysis/generated/census-crosstab.md and analysis/generated/census-worklist.md.
Counts describe the census's records of what the manuscript asserts; they are not
findings about the paper's adequacy. The worklist lists loci where the manuscript's
stated basis at the sentence is a constructed example or the author's own analysis,
so an attestation or a judgment datum would change the basis.
"""
import collections, json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
SRC = ROOT / "analysis/manuscript-census-2026-09-14/census-normalized.json"
OUT = ROOT / "analysis/generated"
SUBS = ["determinative", "common noun", "proper noun", "pronoun", "adjective (control)", "other/mixed/none"]
BASES = [("retained_attestation", "attested"), ("cgel_described", "CGEL"), ("cgel_restricted", "CGEL restr."),
         ("other_source_described", "other source"), ("constructed_ungrammatical", "constr. *"),
         ("constructed_illustration", "constr. illus."), ("authors_analysis", "author's analysis"),
         ("searched_not_found", "searched"), ("not_determinable", "n/d")]
UNCITED = {"constructed_illustration", "constructed_ungrammatical", "authors_analysis"}


def sub(c):
    return c["subcategory"] if c["subcategory"] in SUBS else "other/mixed/none"


def md_table(header, rows):
    out = ["| " + " | ".join(header) + " |", "|" + "|".join("---:" if i else "---" for i in range(len(header))) + "|"]
    out += ["| " + " | ".join(str(x) for x in r) + " |" for r in rows]
    return "\n".join(out)


def main():
    d = json.loads(SRC.read_text())
    claims = d["claims"]
    cons = [c["id"] for c in d["catalogue"]]
    order = sorted(cons, key=lambda k: -sum(1 for c in claims if c["construction_id"] == k))
    lexname = {l["id"]: l["forms"][0] for l in d["lexemes"]}

    # A: construction x subcategory (claims, distinct lexemes)
    rows = []
    for k in order:
        cs = [c for c in claims if c["construction_id"] == k]
        if not cs: continue
        cells = []
        for s in SUBS:
            g = [c for c in cs if sub(c) == s]
            lex = {i for c in g for i in c["lexeme_ids"]}
            cells.append(f"{len(g)} ({len(lex)})" if g else "")
        rows.append([k] + cells + [len(cs)])
    A = md_table(["construction"] + SUBS + ["total"], rows)

    # B: construction x reconciled basis
    rows = []
    for k in order:
        cs = [c for c in claims if c["construction_id"] == k]
        if not cs: continue
        cnt = collections.Counter(c["evidence_type_reconciled"] for c in cs)
        rows.append([k] + [cnt.get(b, "") or "" for b, _ in BASES] + [len(cs)])
    B = md_table(["construction"] + [lab for _, lab in BASES] + ["total"], rows)

    sec = collections.Counter(c["section_label"] for c in claims)
    other = collections.Counter(c["construction_other"] for c in claims if c["construction_other"])
    text = f"""# Census cross-tabulation

<!-- SUMMARY: construction x subcategory and construction x basis over the 658-claim census, from census-normalized.json · status: generated · updated: {d.get('generated', '2026-09-16')} -->

Generated by `analysis/tools/census_tables.py` from `census-normalized.json`. Cells count census claims, with distinct lexemes in parentheses. A claim is one sentence's assertion about one expression in one construction, so a sentence can contribute several claims and a lexeme can appear in many. The basis is `evidence_type_reconciled`: the mechanical signal at the sentence where one exists (attestation footnote, ungrammaticality mark, citation command), otherwise the census's own label. These tables describe the census; they are not a verdict on the manuscript, and `author's analysis` is what a paper proposing an analysis is expected to contain.

## A. Construction by subcategory

{A}

## B. Construction by stated basis at the locus

{B}

Free-text labels for `other`: {", ".join(f"{k} ({v})" for k, v in other.most_common()) or "none"}.
"""
    OUT.mkdir(exist_ok=True)
    (OUT / "census-crosstab.md").write_text(text)

    # worklist
    wl = [c for c in claims if c["evidence_type_reconciled"] in UNCITED and c["construction_id"] not in ("taxonomic_or_meta", "other")
          and c["status"] in ("licensed", "excluded", "conditional")]
    parts = [f"""# Corpus worklist from the census

<!-- SUMMARY: loci where the manuscript's stated basis is a constructed example or its own analysis, grouped by construction and subcategory · status: generated · updated: 2026-09-16 -->

Generated by `analysis/tools/census_tables.py`. Each line is a census claim whose basis at its sentence is `constructed_illustration`, `constructed_ungrammatical` or `authors_analysis` after reconciliation, in a construction the argument uses. An attestation (for licensed or conditional claims) or a judgment datum (for excluded ones) would change the basis recorded here. Nothing on this list is thereby unsupported: a constructed example can be uncontroversial, and the author's analysis is the paper's contribution. The list is ordered by how many census claims the construction carries. {len(wl)} of {len(claims)} claims qualify.

Section load (claims per section, all bases): {", ".join(f"{k} {v}" for k, v in sec.most_common())}.
"""]
    for k in order:
        g = [c for c in wl if c["construction_id"] == k]
        if not g: continue
        parts.append(f"\n## {k} ({len(g)})\n")
        for c in sorted(g, key=lambda c: (SUBS.index(sub(c)), c["expression"].lower(), c["id"])):
            lex = ", ".join(lexname.get(i, i) for i in c["lexeme_ids"]) or c["expression"]
            q = c["quote"].replace("\n", " ")
            q = q if len(q) <= 110 else q[:107] + "..."
            parts.append(f"- `{c['id']}` {sub(c)} · *{lex}* · {c['status']} · {c['evidence_type_reconciled']} · {c['section_label']}: {q}")
    (OUT / "census-worklist.md").write_text("\n".join(parts) + "\n")
    print(f"crosstab: {len(order)} constructions; worklist: {len(wl)}/{len(claims)} claims")


if __name__ == "__main__":
    main()
