#!/usr/bin/env python3
"""Claim register and diagnostic coverage from the normalized census.

Reads analysis/manuscript-census-2026-09-14/census-normalized.json. Writes
  analysis/generated/claim-register.tex   one row per (diagnostic, lexeme): subcategory, statuses, bases, sections, claims
  analysis/generated/claim-coverage.tex   one row per diagnostic: lexemes by subcategory and status
  analysis/generated/claim-register.md    the same register for the repository
`check` verifies the committed .tex files are current.
Excludes claims labelled taxonomic_or_meta or other, and claims with no resolvable lexeme.
"""
import collections, json, sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
SRC = ROOT / "analysis/manuscript-census-2026-09-14/census-normalized.json"
OUT = ROOT / "analysis/generated"
LABEL = {"independent_argument": "independent argument use", "independent_partitive": "independent use with partitive of-PP",
         "dependent_det": "Det before a nominal", "dependent_internal_mod": "internal Mod before a nominal",
         "internal_mod_admission": "admits an internal modifier", "peripheral_mod_admission": "admits a peripheral modifier",
         "external_determination": "takes an external determiner", "degree_modifier_adj": "degree modifier of an adjective",
         "degree_modifier_nonadj": "degree modifier of a non-adjective", "predicative_complement": "predicative complement",
         "comparative_complement": "comparative than-complement", "existential_displaced_subject": "existential displaced subject",
         "number_agreement": "number agreement or transparency", "number_inflection": "number inflection", "grade_inflection": "grade inflection",
         "genitive_marking": "genitive marking", "predeterminer_mod": "predeterminer modifier", "coordination_marker": "marker of coordination",
         "compound_base": "base of a compound determinative", "fused_head": "fused-head analysis", "relative_postmod_admission": "relative postmodifier"}
BASIS = {"retained_attestation": "attested", "cgel_described": "CGEL", "cgel_restricted": "CGEL (restricted)", "other_source_described": "other source",
         "constructed_illustration": "constructed", "constructed_ungrammatical": "constructed (starred)", "authors_analysis": "analysis",
         "searched_not_found": "searched, none", "not_determinable": "n/d"}
SUBS = ["determinative", "common noun", "proper noun", "pronoun", "adjective (control)"]


def tex(s):
    return s.replace("&", "\\&").replace("%", "\\%").replace("_", "\\_").replace("#", "\\#")


def main():
    d = json.loads(SRC.read_text()); lex = {l["id"]: l for l in d["lexemes"]}
    rows = collections.defaultdict(lambda: {"claims": 0, "status": collections.Counter(), "basis": collections.Counter(), "sections": set(), "sub": None})
    for c in d["claims"]:
        if c["construction_id"] in ("taxonomic_or_meta", "other") or not c["lexeme_ids"]:
            continue
        for lid in c["lexeme_ids"]:
            r = rows[(c["construction_id"], lex[lid]["forms"][0].lower())]
            r["claims"] += 1; r["status"][c["status"]] += 1; r["basis"][c["evidence_type_reconciled"]] += 1
            r["sections"].add(c["section_label"].replace("sec:", "")); r["sub"] = lex[lid].get("subcategory") or "other"
    order = sorted({k[0] for k in rows}, key=lambda k: (-sum(rows[x]["claims"] for x in rows if x[0] == k), k))
    reg, md = [], ["# Claim register", "", "<!-- SUMMARY: every participation claim in the census by diagnostic and lexeme, with status and stated basis; generated by analysis/tools/claim_register.py · status: generated · updated: 2026-09-17 -->", "",
                   "| Diagnostic | Lexeme | Subcategory | Status | Basis | Sections | Claims |", "|---|---|---|---|---|---|---:|"]
    for con in order:
        for (c, form), r in sorted(((k, v) for k, v in rows.items() if k[0] == con), key=lambda kv: (SUBS.index(kv[1]["sub"]) if kv[1]["sub"] in SUBS else 9, kv[0][1])):
            st = ", ".join(f"{k} {v}" if v > 1 else k for k, v in r["status"].most_common())
            ba = ", ".join(f"{BASIS.get(k, k)} {v}" if v > 1 else BASIS.get(k, k) for k, v in r["basis"].most_common())
            secs = ", ".join(sorted(r["sections"]))
            reg.append(f"{tex(LABEL.get(con, con))} & \\mention{{{tex(form)}}} & {tex(r['sub'])} & {tex(st)} & {tex(ba)} & {tex(secs)} & {r['claims']} \\\\")
            md.append(f"| {LABEL.get(con, con)} | *{form}* | {r['sub']} | {st} | {ba} | {secs} | {r['claims']} |")
    cov = []
    for con in order:
        cells = []
        for s in SUBS:
            g = [(k, v) for k, v in rows.items() if k[0] == con and v["sub"] == s]
            if not g: cells.append(""); continue
            lic = sum(1 for k, v in g if v["status"]["licensed"] or v["status"]["conditional"]); exc = sum(1 for k, v in g if v["status"]["excluded"] and not (v["status"]["licensed"] or v["status"]["conditional"]))
            cells.append(f"{len(g)} ({lic}/{exc})")
        tot = len([k for k in rows if k[0] == con])
        cov.append(f"{tex(LABEL.get(con, con))} & " + " & ".join(cells) + f" & {tot} \\\\")
    body_reg, body_cov = "\n".join(reg) + "\n", "\n".join(cov) + "\n"
    if len(sys.argv) > 1 and sys.argv[1] == "check":
        ok = (OUT / "claim-register.tex").read_text() == body_reg and (OUT / "claim-coverage.tex").read_text() == body_cov
        sys.exit(0 if ok else "claim register is stale; run: python3 analysis/tools/claim_register.py")
    OUT.mkdir(exist_ok=True)
    (OUT / "claim-register.tex").write_text(body_reg); (OUT / "claim-coverage.tex").write_text(body_cov)
    (OUT / "claim-register.md").write_text("\n".join(md) + "\n")
    print(f"register rows {len(reg)}; coverage rows {len(cov)}; claims covered {sum(r['claims'] for r in rows.values())}")


if __name__ == "__main__":
    main()
