#!/usr/bin/env python3
"""Coverage of the extracted claim set by construction and noun subcategory.

The paper argues that common noun, proper noun, pronoun and determinative are
four coordinate subcategories of Noun (determinatives-as-nouns.tex:716).  A
diagnostic that separates or unites those subcategories is worth more when it
has been applied across them.  This script reports, per construction, which
subcategories the claim set actually covers.

IMPORTANT: absence from the claim set is not absence from the manuscript.  The
extraction is "a bounded selection from the full documents, not an exhaustive
inventory" (expanded-json-2026-09-14/README.md).  Every gap this reports is a
place to look in the manuscript, not a finding about the manuscript.

SUBCATEGORY assignments below are the analyst's, grounded in the manuscript
lines cited in the `why' field.  They are not a field in records.json; the
lexeme entries carry only id and forms.
"""

import json
import sys
from collections import defaultdict
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
RUN = ROOT / "analysis" / "expanded-json-2026-09-14"
ENRICHED = ROOT / "analysis" / "claims" / "claims-enriched.json"

# The four coordinate subcategories the paper's taxonomy asserts.
FOUR = ["determinative", "common noun", "pronoun", "proper noun"]

# Manuscript verification of the gaps the claim set shows, done by hand against
# determinatives-as-nouns.tex on 2026-09-14.  Line numbers are from that file.
# This is what keeps a claim-set gap from being reported as a manuscript gap.
VERIFIED = {
    "dependent_det": (
        "artifact",
        "L118 gives Det function for a pronoun (*my preferences*), a proper noun "
        "(*Kim's preferences*) and a common noun (*people's preferences*), citing "
        "CGEL 354-355, 470-471. The manuscript covers 4/4 here; the extraction "
        "simply did not select that passage."),
    "peripheral_mod_admission": (
        "partly artifact",
        "Sec. `Modifier selection and attachment' gives *only you* (pronoun) and "
        "*Usually a careful driver, Anne found...* (common noun) alongside "
        "*almost every experienced teacher*. Manuscript covers 3/4; proper noun "
        "remains untested."),
    "comparative_complement": (
        "principled",
        "L164 groups comparative complementation with grade and degree-modifier "
        "selection as an *adjectival* property, weighed as a counterweight. "
        "Four-way nominal coverage is not expected and its absence is not a gap."),
    "dependent_internal_mod": (
        "principled",
        "This is the adjectival control construction of Sec. 2.3 (*numerous "
        "people* against *many people*). It exists to contrast with the nominal "
        "diagnostics, not to be one."),
}


def main():
    if not ENRICHED.exists():
        sys.exit("run analysis/claims/enrich.py first")
    records = json.loads(ENRICHED.read_text())
    SUBCATEGORY = {l["id"]: (l["subcategory"], l["subcategory_grounding"])
                   for l in records["lexemes"]}
    supplement = {e["query_id"] for e in json.loads((RUN / "supplement-cell-map.json").read_text())}

    by_con = defaultdict(lambda: defaultdict(list))
    for c in records["participation_claims"]:
        sub = SUBCATEGORY[c["lexeme_id"]][0]
        block = "supplement" if c["id"] in supplement else "manuscript"
        by_con[c["construction_id"]][sub].append((c["id"], c["form"], block))

    out = []
    out.append("# Claim-set coverage by construction and noun subcategory\n")
    out.append("Generated by `analysis/tools/coverage.py` from "
               "`analysis/expanded-json-2026-09-14/records.json`.\n")
    out.append("The paper argues that common noun, proper noun, pronoun and determinative are "
               "four coordinate subcategories of Noun. A diagnostic carries more weight when it "
               "has been applied across them. This table reports what the *claim set* covers.\n")
    out.append("**Absence here is not absence from the manuscript.** The extraction is a bounded "
               "selection, so each gap is a place to check, not a finding.\n")

    # Per-subcategory totals.
    totals = defaultdict(int)
    lex_totals = defaultdict(set)
    for c in records["participation_claims"]:
        sub = SUBCATEGORY[c["lexeme_id"]][0]
        totals[sub] += 1
        lex_totals[sub].add(c["lexeme_id"])
    out.append("## Claims by subcategory\n")
    out.append("| Subcategory | Lexemes | Claims |")
    out.append("|---|---:|---:|")
    for sub in FOUR + ["adjective (control)"]:
        out.append(f"| {sub} | {len(lex_totals[sub])} | {totals[sub]} |")
    out.append("")

    empty = [s for s in FOUR if not totals[s]]
    thinnest = [s for s in FOUR if 0 < totals[s] <= 2]
    out.append("## The two legs that carry least\n")
    if empty:
        out.append(f"**{', '.join(empty)}: no claims at all**, across all "
                   f"{len(by_con)} constructions. The manuscript is not silent on proper nouns, "
                   "but what it has is taxonomic statement plus three data points borrowed from "
                   "*CGEL* (*Kim's preferences* L118, *the Smiths* L184, *Kim left* L370) and two "
                   "restrictive property claims (L148, L734). Exactly one of the paper's eleven "
                   "constructions has a proper-noun instance anywhere in the manuscript "
                   "(*Kim's preferences* in Det function); the other ten have none. L726 "
                   "concedes the point: "
                   "extending the feature matrix to common nouns, proper nouns and adjectives "
                   "\"would require new sampling, feature selection, and coding across all "
                   "groups.\"\n")
    for s_ in thinnest:
        out.append(f"**{s_}: {totals[s_]} claim{'' if totals[s_] == 1 else 's'}** "
                   f"({', '.join(sorted(l for l in lex_totals[s_]))}). The manuscript adds "
                   "*poor old me* (L732), *She left* (L370), *only you* (modifier section) and "
                   "the case/genitive discussion (L190), all CGEL-cited.\n")
    out.append("The determinative and common-noun legs carry "
               f"{totals['determinative']} and {totals['common noun']} claims. The taxonomy is "
               "four-way; the evidence is close to two-way, with an adjectival contrast class "
               f"({totals['adjective (control)']} claims) doing more work than two of the four "
               "subcategories it is meant to sit beside.\n")
    out.append("## Evidence type\n")
    claims = records["participation_claims"]
    et = defaultdict(int)
    prov = defaultdict(int)
    for c in claims:
        et[c["evidence_type"]] += 1
        prov[c["evidence_type_provenance"]] += 1
    out.append(f"All {len(claims)} claims now carry an evidence_type. The 54 supplement claims "
               "declare their basis in the supplement's table; the other 56 were assigned by the "
               "re-extraction of 2026-09-14, which reproduced all 54 declared values correctly "
               "with them withheld.\n")
    out.append("| Evidence type | Claims |")
    out.append("|---|---:|")
    for k, v in sorted(et.items(), key=lambda kv: -kv[1]):
        out.append(f"| `{k}` | {v} |")
    out.append("")

    supplement_ids = {e["query_id"] for e in
                      json.loads((RUN / "supplement-cell-map.json").read_text())}
    sup_att = sum(1 for c in claims if c["id"] in supplement_ids
                  and c["evidence_type"] == "retained_attestation")
    attested = et.get("retained_attestation", 0)
    cgel = et.get("cgel_described", 0) + et.get("cgel_restricted", 0)
    constructed = et.get("constructed_illustration", 0) + et.get("constructed_ungrammatical", 0)
    own = et.get("authors_analysis", 0)
    searched = et.get("searched_not_found", 0)
    out.append("> **These counts describe the extracted claim set, not the manuscript.**\n"
               "> The 54 supplement claims are a complete enumeration of one table and can be\n"
               "> counted. The 56 manuscript claims are a convenience sample: the extraction that\n"
               "> produced them was asked for \"approximately 80-110 NEW participation queries\",\n"
               "> a quota, and its own README calls the result \"a bounded selection from the full\n"
               "> documents, not an exhaustive inventory\". No sampling frame was defined, so\n"
               "> proportions over them do not estimate anything about the paper. The worked\n"
               "> example of Figure 6, *the lucky few*, appears eight times in the manuscript and\n"
               "> has no record in the set at all.\n")
    out.append(f"Within the 54-claim supplement enumeration: {sup_att} rest on a retained "
               f"attestation and {54 - sup_att} do not. That table was built cell by cell, so "
               "this proportion is meaningful.\n")
    out.append(f"Across all {len(claims)} extracted claims the labels fall out as {attested} "
               f"attested, {cgel} CGEL-described, {constructed} constructed, {own} the author's "
               f"own analysis, {searched} searched-not-found. Reported for completeness; do not "
               "read the manuscript-block share as a property of the paper.\n")

    by_con_et = defaultdict(lambda: defaultdict(int))
    for c in claims:
        by_con_et[c["construction_id"]][c["evidence_type"]] += 1
    rows = []
    for con, d in by_con_et.items():
        tot = sum(d.values())
        rows.append((d.get("retained_attestation", 0), tot, con))
    rows.sort(key=lambda r: (r[0] / r[1], -r[1]))
    out.append("Per construction, ordered by how little attestation supports it:\n")
    out.append("| Construction | Attested | Claims | Share |")
    out.append("|---|---:|---:|---:|")
    for att, tot, con in rows:
        out.append(f"| `{con}` | {att} | {tot} | {att / tot:.0%} |")
    out.append("")
    naked = [c for a, t, c in rows if a == 0]
    out.append(f"{len(naked)} of {len(rows)} constructions have no attested claim *in the "
               "extracted set*: " + ", ".join(f"`{c}`" for c in naked) + ". Every one of these "
               "is carried mostly or wholly by the convenience sample, so this is a fact about "
               "what was extracted. It is not a list of gaps in the paper and must not be read "
               "as a corpus worklist.\n")
    out.append("One caveat on the extracted 56: the extraction was offered `not_determinable` "
               "and never used it. Its 54/54 on the withheld key is good evidence against "
               "confabulation, but a single label is still being forced onto evidence that is "
               "sometimes mixed (X061 marks *so numerous mistakes* constructed_ungrammatical "
               "while noting it also carries a CGEL citation).\n")

    out.append("## Coverage by construction\n")
    out.append("`n/4` counts how many of the four coordinate subcategories appear. "
               "Adjective controls are listed but not counted, since the paper uses them as a "
               "contrast class rather than a noun subcategory.\n")
    out.append("| Construction | n/4 | Determinative | Common noun | Pronoun | Proper noun | Adj (control) |")
    out.append("|---|---:|---|---|---|---|---|")

    def cell(entries):
        if not entries:
            return "~"
        forms = sorted({f for _, f, _ in entries})
        return ", ".join(f"*{f}*" for f in forms)

    order = sorted(by_con, key=lambda k: -sum(len(v) for v in by_con[k].values()))
    for con in order:
        subs = by_con[con]
        n = sum(1 for s in FOUR if subs.get(s))
        row = [con, f"**{n}/4**"] + [cell(subs.get(s, [])) for s in FOUR] + [cell(subs.get("adjective (control)", []))]
        out.append("| " + " | ".join(row) + " |")
    out.append("")

    thin = [c for c in order if sum(1 for s in FOUR if by_con[c].get(s)) <= 1]
    out.append("## Constructions resting on a single subcategory\n")
    out.append(f"{len(thin)} of {len(order)} constructions have claims from at most one of the "
               "four coordinate subcategories:\n")
    for c in thin:
        subs = [s for s in FOUR if by_con[c].get(s)]
        n_claims = sum(len(v) for v in by_con[c].values())
        plural = "claim" if n_claims == 1 else "claims"
        out.append(f"- `{c}` ({n_claims} {plural}): "
                   f"{subs[0] if subs else 'none of the four'} only")
        verdict, note = VERIFIED.get(c, ("unchecked", "Not yet checked against the manuscript."))
        out.append(f"  - **{verdict}**: {note}")
    out.append("")
    out.append("`artifact` means the manuscript covers what the claim set does not, so the gap is "
               "in the extraction. `principled` means four-way coverage is not expected there. "
               "Neither is a defect in the paper.\n")

    out.append("## Subcategory assignments used\n")
    out.append("| Lexeme | Subcategory | Grounding |")
    out.append("|---|---|---|")
    for lid, (sub, why) in sorted(SUBCATEGORY.items(), key=lambda kv: (kv[1][0], kv[0])):
        out.append(f"| `{lid}` | {sub} | {why} |")

    dest = ROOT / "analysis" / "coverage-2026-09-14.md"
    dest.write_text("\n".join(out) + "\n")
    print(f"wrote {dest.relative_to(ROOT)}")
    print("\n".join(out[:0]))
    return 0


if __name__ == "__main__":
    sys.exit(main())
