from pathlib import Path
import re

p = Path('determinatives-as-nouns.tex')
s = p.read_text()
baseline = Path('notes/snapshots/2026-09-11-final-author-review/determinatives-as-nouns.tex').read_text()
assert s == baseline, 'Source changed since author-review snapshot'

def replace(old, new):
    global s
    assert s.count(old) == 1, (s.count(old), old[:110])
    s = s.replace(old, new)

replace(r"I examine restricted articles, reconsider independent \mention{what}'s pronoun classification, and address determinatives' degree-modifier uses.", r"I examine restricted articles and determinatives' degree-modifier uses.")
replace('Their unification is one structural consequence of the proposal.', 'Their unification is one structural consequence of the D-noun proposal.')
replace(r'and redistributes other determinatives. Her grounds', r'and redistributes other determinatives among adjectives and pronouns \citep[194--195]{spinillo2004reconceptualising}. Her grounds')
replace('differences within the trio.', 'differences within the article trio.')
replace(r"The determinative inventory includes the reassignment of independent \mention{what} and relative \mention{which} argued for in §\ref{sec:wh-boundary}.", r"The determinative inventory includes independent \mention{what} and relative \mention{which}, as explained in §\ref{sec:wh-boundary}.")
replace(r"Interrogative, relative, and exclamative properties must be distinguished from those functions. An interrogative object may be headed by a pronoun (\mention{who}) or a common noun (\mention{which book}); the latter obtains its interrogative property from a dependent. Similarly, \mention{What a nice day!} requires exclamative \mention{what}; substituting an ordinary NP doesn't preserve the construction. \textit{CGEL} classifies this \mention{what} as an adjective, distinct from interrogative and relative \mention{what} \citep[433--437; Ch.~10, §7]{huddleston2002}.", r"Interrogative and relative properties must be distinguished from those functions. An interrogative object may be headed by a pronoun (\mention{who}) or a common noun (\mention{which book}); the latter obtains its interrogative property from a dependent. Neither the object function nor the interrogative construction determines the lexical head's category.")
start = s.index('Inflection supplies overlapping contrasts too.')
end = s.index('The adjectival affinities likewise', start)
s = s[:start] + s[end:]
replace(r"Plain determinatives, including modified forms such as \mention{almost ten}, join genitives such as \mention{Kim's} and \mention{my}.", r"Plain determinative-headed NPs, such as \mention{almost ten} in \mention{almost ten apples}, join genitives such as \mention{Kim's} and \mention{my}.")

start = s.index('The systematic use of AdvP premodifiers')
end = s.index(r'\subsection{Word formation', start)
s = s[:start] + r'''Adverbial premodification needs two levels distinguished. Within a common-noun Nom, premodifiers are normally adjectival or nominal. At the edge of a whole NP, adverbs are less restricted: compare \mention{only you}, \mention{for almost my entire life}, and \mention{Usually a careful driver, Anne found her mind wandering}. Here \mention{only}, \mention{almost}, and \mention{usually} modify NPs containing their own heads and, where present, determiners. \textit{CGEL} calls these \term{peripheral modifiers} \citep[430--431]{huddleston2002}.

Could \mention{almost} in \mention{almost every} likewise modify the whole determinative-headed NP? Once DP is replaced by NP, that becomes an available analysis. \textit{CGEL} itself observes overlap between DP modifiers and peripheral NP modifiers, with some attachment decisions uncertain \citep[431]{huddleston2002}. Figure~\ref{fig:every} retains internal attachment, but the dependent use alone doesn't establish it: either attachment can place \mention{almost every} together in Det function.

Treating every pre-head adverb as peripheral would require more. In the constructed \mention{the very few who objected}, \mention{very} follows the external determiner and modifies \mention{few} within Nom. A peripheral analysis would need an additional embedded NP or another structural change. The ordinary nominal structure therefore still needs internal AdvP modification for some determinatives, although \mention{almost every} alone isn't decisive evidence for it.

NP modifiers provide a further connection. Determinatives permit determinative premodifiers such as \mention{this} in \mention{this much} \citep[393]{huddleston2002}. Under the proposed analysis, this is an NP modifier in another NP. Comparative determinatives also take established NP modifiers: \mention{a lot} in \mention{a lot fewer}, alongside \textit{CGEL}'s \mention{a lot more than fifty} \citep[432]{huddleston2002}. These permissions remain specific to the head and construction.

\textcite[42--47]{payne2010} establish that adverbs can postmodify common nouns, as in the constructed \mention{the changes globally to the climate}. They also analyse \mention{almost} as modifying the attributive nominal \mention{textbook} in \mention{an almost textbook case} \citep[p.~75, n.~3]{payne2010}. Adverbial modification therefore isn't categorically excluded from Noun, even internally. Its broader availability with determinatives remains a difference of distribution within the proposed category.

Postmodifier permissions also overlap. Common nouns freely take integrated relative clauses; personal pronouns permit a restricted range, including \mention{we who have read the report} \citep[430]{huddleston2002}. Determinative examples include \mention{few who come ever leave}, \mention{those who came}, \mention{that which remains}, and \mention{something that you need to know}. Section~\ref{sec:modification} examines this shared construction.

The resulting comparison is narrower than a contrast between nouns and adverb-modified determinatives. Peripheral modification already belongs to NP grammar; some internal adverbial modification occurs with common nouns too. Determinatives nevertheless permit internal modifier patterns that ordinary common-noun heads exclude. Section~\ref{sec:costs} counts the necessary subcategory restrictions in comparing the grammars.

\subsection{Inflection}\label{sec:inflection}

Inflection supplies several connections with established nouns, though no one contrast runs through the whole category. Common nouns typically distinguish singular and plural; proper nouns permit number inflection in restricted uses such as \mention{the Smiths}. Demonstratives likewise distinguish \mention{this}/\mention{these} and \mention{that}/\mention{those} \citep[373, 521]{huddleston2002}. These are contrasts between forms of a lexeme, unlike the fixed number restrictions of \mention{each} and \mention{several}.

Number needn't be inflectional wherever it matters. \textit{CGEL} treats singular and plural \mention{you} as distinct lexemes, differentiated overtly only by the reflexive forms \mention{yourself} and \mention{yourselves} \citep[486]{huddleston2002}. Number-neutral \mention{some} has no corresponding singular--plural alternation. The demonstratives supply positive morphological evidence; the absence of that alternation elsewhere doesn't distinguish determinatives from pronouns as whole categories.

Case offers another partial connection. Common and proper nouns have genitives, while personal pronouns have fuller case paradigms. Determinative compounds permit genitives such as \mention{someone's} and \mention{something's}, though their nominal components may contribute to this permission \citep[423--424, 479--480]{huddleston2002}. Most determinatives lack case inflection. Genitive marking consequently supports the compounds' nominal affinity more directly than the category's membership as a whole.

Grade instead connects determinatives with adjectives. The paradigms \mention{few}/\mention{fewer}/\mention{fewest}, \mention{many}/\mention{more}/\mention{most}, and their counterparts with \mention{little} and \mention{much} distinguish plain, comparative, and superlative forms \citep[391--395]{huddleston2002}. This is a property of a restricted quantificational group. Demonstratives and articles lack grade, just as most determinatives lack case.

Finally, \mention{no}/\mention{none} distinguishes dependent and independent forms, paralleling the distinction within genitive \mention{my}/\mention{mine} (§\ref{sec:enough}). Inflection thus supports both nominal and adjectival connections. The clearest nominal comparison is demonstrative number; grade is the clearest counterweight. Neither can serve as a necessary condition for the whole superordinate category.

''' + s[end:]
replace('Derivation supplies a less uniform comparison than inflection.', 'Derivation connects categories through word formation, but the output category need not identify the input.')
replace(r"Numeral morphology extends the comparison to ordinal and fractional formations, analysed respectively as adjectival and nominal by \textcite{reynolds2026numerals}. Their formation also bears on the boundary between a numeral lexeme and a syntactic phrase.", r"Numeral morphology requires the input categories to be kept distinct. \textcite[§5.4]{reynolds2026numerals} derives fractional nouns from cardinal nouns: \mention{seventh}, for example, is a count noun in \mention{three sevenths}. This isn't independent evidence that determinative \mention{seven} is a noun. The analysis already distinguishes a nominal cardinal base from the determinative one. Ordinal \mention{seventh}, as in \mention{the seventh attempt}, is adjectival." + '\n\n' + r"Larger numerals also require syntax. In \mention{two thousand and twenty-seventh}, only the final coordinate is an AdjP; the preceding cardinal phrase retains its own category \citep[§5.5]{reynolds2026numerals}. Suffixation on the rightmost base doesn't turn the entire coordination into an adjective lexeme. The present proposal changes the superordinate category of determinatives while preserving these distinctions between lexemes, phrases, and coordinates.")
replace('Morphology supplies mixed evidence: number and genitive marking give the clearest inflectional connections with nouns, while grade gives an adjectival connection. Derivation links some determinatives with common nouns through suffixes whose typical bases are adjectival.', 'Word formation therefore provides connections without a uniform category diagnostic. Several determinatives supply bases for common nouns, but the relevant suffixes also select other categories. The stronger morphological comparisons remain the inflectional contrasts in the preceding subsection.')

# Upright brackets, including in italic object-language examples.
s = re.sub(r'\\mention\{([^{}]*)\}', lambda m: r'\mention{' + m[1].replace('[', r'\textup{[}').replace(']', r'\textup{]}') + '}', s)
replace('Adjectival independent uses prevent a simple inference from these positions to nounhood.', r'Independent uses containing fused-head AdjPs prevent a simple inference from these positions to nounhood.')
replace('without a human-class interpretation', 'without a generic human interpretation')
replace('normally requires a determiner on the human-class reading.', r'requires the definite article \mention{the} on the generic human reading \citep[417--418]{huddleston2002}.')
replace('Such examples don\'t decide whether the restriction belongs in semantics or syntax.', r"Generic pronoun \mention{one}, as in \mention{One shouldn't judge}, provides a parallel without a required overt antecedent. Such examples don't decide whether the restriction belongs in semantics or syntax.")
replace(r"\textit{CGEL} also uses fusion with nouns. It assigns anaphoric \mention{mine} to Det--Head, but predicative possessive \mention{mine}, as in \mention{it's mine}, to pure Head \citep[410--411]{huddleston2002}. Nounhood is thus compatible with fusion. Here ordinary determinative headedness follows from the inherited projection rules; the analysis of independent genitives, including \mention{Kim's} and \mention{mine}, falls outside the fragment in §\ref{sec:fragment}.", r"\textit{CGEL} also uses fusion with nouns. Anaphoric \mention{mine}, understood as \enquote{my car}, combines the possessive relation with an understood nominal description and receives a fused analysis. Predicative \mention{mine}, as in \mention{it's mine}, can instead mean \enquote{belongs to me}: it expresses the relation directly, without an understood nominal head \citep[410--411, 470--471]{huddleston2002}. A suitable context may permit either reading." + '\n\n' + r"This distinction shows why nounhood and fusion are compatible. Ordinary determinative headedness follows here from the proposed projection rules; it doesn't require eliminating every fused construction containing a noun. The analysis of independent genitives, including \mention{Kim's} and \mention{mine}, falls outside the fragment in §\ref{sec:fragment}.")
replace('involving both external determination and adjectival modification.', 'involving both an external determiner and an attributive-modifier AdjP.')
replace(r"\mention{some that I saw}.", r"\mention{some that I saw} and \mention{two that I have seen}.")
replace(r'The human-class \mention{the rich}', r'The generic human \mention{the rich}')
replace(r"\textit{CGEL}'s \mention{Henrietta likes red shirts, and I like blue} permits colour-noun ambiguity as well as possible reduction licensed by coordination; the attested \mention{Bluer is better} establishes a bare comparative subject without settling its phrase category.", r"\textit{CGEL}'s \mention{Henrietta likes red shirts, and I like blue} permits reduction licensed by coordination. The constructed \mention{Blue is good} raises a separate ambiguity between noun and adjective, while the attested \mention{Bluer is better} establishes a bare comparative subject without settling its phrase category.")
replace(r'\mention{She is a doctor}', r'\mention{She is a beauty}')

start = s.index('Should determinatives and pronouns be coordinate')
end = s.index(r'\section{Restricted members', start)
s = s[:start] + r'''Including determinatives within Noun leaves a second question: where within Noun do they belong? In the proposed hierarchy, common noun, proper noun, pronoun, and determinative are four coordinate subcategories. Hudson instead puts determinative inside pronoun, which is itself inside Noun. Both group determinatives with nouns. They differ in whether pronouns and determinatives form an intermediate category that excludes common and proper nouns.

The intermediate category would be useful if it supported grammatical generalizations applying to pronouns and determinatives together. The coordinate analysis can still record properties shared by those two groups; it doesn't claim that every noun subcategory is equally similar to every other. The issue is whether their shared properties warrant another level in the lexical hierarchy.

\textcite{reynolds2021} investigates their similarity by applying an unsupervised clustering model to a matrix of word forms and properties. Each entry records whether a form has a property, such as permitting \mention{almost} as a modifier or having a genitive form. The study reports 232 properties for 138 word forms. Clustering groups forms by their recorded similarities without being told which forms are pronouns and which are determinatives.

The resulting groups broadly resemble the supplied pronoun and determinative inventories, although the outcome varies with the starting configuration and the properties included.\footnote{The public file contains 155 properties for the same 138 forms, despite the reported 232. The accompanying \href{run:matrix-audit.pdf}{\textit{Replication audit of the English determinative--pronoun feature matrix}} documents this discrepancy, reproduces the published statistical decomposition, and examines sensitivity to starting configuration and feature selection. The public file is preserved unchanged.} This supports a distinction between the groups. It doesn't decide where to place that distinction in a larger hierarchy.

Two subcategories can be clearly distinguishable while sharing a parent. The study therefore leaves both a broader pronoun category and the present broader Noun category open. It also contains no common or proper nouns, so it cannot test whether determinatives are closer to pronouns than to those alternatives. Its inventories follow \textit{CGEL}; the small boundary revisions in §\ref{sec:wh-boundary} would require a correspondingly revised comparison.

The grammatical case for nesting must consequently be assessed on its own. Many pronouns and determinatives have little descriptive content and depend on context for interpretation. Pro-form gender supplies further connections (§\ref{sec:membership}). These properties make the grouping plausible, but they don't uniquely identify it: primary naming uses of proper nouns also depend on context, and pro-form gender extends to non-nominal expressions \citep{reynolds2025proformgender}.

Restrictions on determination and modification are another candidate. Personal pronouns generally resist external determiners and permit few internal modifiers: \mention{poor old me} illustrates the restricted adjectival pattern \citep[429--430]{huddleston2002}. But proper names also resist free determination and modification in their primary uses \citep[517, 519--520]{huddleston2002}. These restrictions don't pick out pronouns and determinatives alone.

Nor are those restrictions uniform within the proposed intermediate category. Determinatives allow \mention{the few}, \mention{the two}, and \mention{these three}, with item-specific conditions; \textit{CGEL} gives \mention{these few here} and \mention{the many who did} \citep[415--416]{huddleston2002}. Their adverbial modifier patterns differ from the restricted adjectival pattern of personal pronouns. A broader pronoun category couldn't simply pass the personal pronouns' rules down to determinatives.

I therefore place determinative alongside pronoun. Their shared nominal structure belongs at the Noun level, while their more specific patterns remain distinct: person, case, and reflexivity organize much of the pronoun system; quantification, determination, and degree organize much of the determinative system. Nesting remains a coherent alternative, but the comparisons here don't establish a further shared set of grammatical rules that requires it.

''' + s[end:]
replace(r"\citep[371--372, 410--411]{huddleston2002}.\footnote{In \mention{the bigger the better}, \textit{CGEL} analyses \mention{the} as a modifier within a comparative phrase \citep[1131--1132, 1135--1136]{huddleston2002}. This dependent use outside Det leaves the restriction on ordinary argument use intact.}", r"\citep[371--372, 410--411]{huddleston2002}.")
replace(r"The pronoun's paradigm supports its membership despite its lack of \mention{mine}'s independent distribution.", r"Dependent \mention{my} and independent \mention{mine} belong to one pronoun paradigm. \mention{My} remains a noun even though, in the ordinary NP construction, it requires a following nominal.")
replace(r"Their connections extend beyond shared position, although neither has the full determinative profile \citep[368--373]{huddleston2002}.", r"Their connections extend beyond shared position, although neither has the full determinative profile \citep[368--373]{huddleston2002}." + '\n\n' + r"\mention{The} also participates in degree modification. In \mention{the bigger the better}, it modifies comparative AdjPs, as other determinatives do in \mention{much bigger} or \mention{no better} \citep[1131--1132, 1135--1136]{huddleston2002}. This supplies a connection outside ordinary Det function while preserving its exclusion from independent argument use.")
start = s.index(r'\mention{Who} has positive morphological')
end = s.index(r'\subsection{Form selection', start)
s = s[:start] + r'''The pronoun boundary matters for the inventory, but either categorization keeps the disputed forms within Noun. I retain \mention{who} as a pronoun: its \mention{who}/\mention{whom}/\mention{whose} paradigm gives positive case evidence, though no single property is definitive \citep[904--905]{huddleston2002}. I treat interrogative and relative \mention{what} as determinative across dependent and independent uses.

\textit{CGEL}'s split treatment of \mention{what} rests on gender: dependent \mention{what} allows personal and non-personal heads, whereas independent \mention{what} is non-personal \citep[398]{huddleston2002}. Compare \mention{What person/object do you have in mind?} with \mention{What's behind the door?} I state this as a constructional restriction: an overt nominal supplies its own descriptive restriction; without one, the independent construction requires a non-personal interpretation. Independent use alone doesn't require a pronoun analysis.

Interrogative \mention{which} already remains determinative across both uses in \textit{CGEL}. I extend that continuity to relative \mention{which}, preserving its non-personal restriction when independent \citep[397--399]{huddleston2002}. This leaves partitive and relative-clause permissions to be stated separately. The proposal concerns these lexical boundaries; its superordinate-Noun argument doesn't depend on their precise placement.\footnote{Exclamative \mention{what}, as in \mention{What a nice day!}, retains the distinct adjective analysis in \textit{CGEL} \citep[436--437]{huddleston2002}.}

''' + s[end:]
replace(r"Noun membership doesn't confine every projection to argument or determiner function.", r"Noun membership doesn't confine every projection to argument or determiner function.\footnote{\mention{Both}, \mention{either}, and \mention{neither} also serve as markers of coordination \citep[1305--1306]{huddleston2002}. Their noun categorization would preserve that further category--function combination; the present fragment doesn't analyse coordination.}")
replace('This shares a phrase type without shortening the selectional disjunction:', 'Determinative phrases and genitive NPs supply the principal realizations in the separate-D analysis; PPs are restricted. Under ordinary headedness, NP covers both principal types. This consolidation leaves the selectional conditions in place:')
replace(r"Table~\ref{tab:permissions} records \term{use permissions}: whether a form, on a given reading, can head a phrase in determiner, subject, or object function. \term{Argument use} covers the subject and object NPs in examples such as \mention{Some left} and \mention{I saw some}.", r"Table~\ref{tab:permissions} records \term{use permissions}. \term{Dependent} means that the form heads a phrase in Det function before another nominal. \term{Independent} means that its phrase occurs without another nominal in the displayed subject or object uses, as in \mention{Some left} and \mention{I saw some}. These labels describe the constructions covered here, rather than every possible function.")
replace('Form & Det use & Argument use & Target in the Det construction', 'Form & Dependent & Independent & Target in the Det construction')
replace(r'\mention{my} & yes & no & No number/count restriction in this fragment', r'\mention{my} & yes & no & No count or number restriction')
replace(r'\mention{she} & no & yes & None', r'\mention{she} & no & yes & Not applicable')
replace('D--Nom--NP through cross-category projection', 'D remains separate but heads Nom and NP')
replace('NP distribution through Det--Head \\', 'NP distribution through Det--Head fusion \\')
replace(r"\mathrm{NP}_{h} &\to (\mathrm{Det})\quad \mathrm{Head}:\mathrm{Nom}_{h}", r"\mathrm{NP}_{h} &\to (\mathrm{Mod}_{\mathrm{periph}})\quad (\mathrm{Det})\quad \mathrm{Head}:\mathrm{Nom}_{h}")
replace("The head's entry and construction restrict every dependent.", r"The head's entry and construction restrict every dependent. \(\mathrm{Mod}_{\mathrm{periph}}\) adds the peripheral premodifier discussed in §\ref{sec:payne}; the compact rule leaves any further NP layering implicit.")
replace(r"The outer NP takes its argument permission from \mention{apple}, whose requirement for determination is satisfied by the article.", r"The outer NP takes its argument permission from \mention{apple}, whose requirement for determination is satisfied by the article." + '\n\n' + r"The same distinction between phrase levels matters beyond the fragment. In \mention{I know which apple it is}, \mention{which} heads the determining phrase inside \mention{which apple}. The whole \mention{which apple} is the preposed predicative complement of \mention{is} in the embedded interrogative clause. Its function doesn't make \mention{which} independent; \mention{apple} still heads that NP.")
replace(r"The premodifier contrast in §\ref{sec:payne} adds a cost. A restriction normally stated for primary Noun now applies to specified noun subcategories, while determinatives retain their adverbial premodifiers. The attributive \mention{almost textbook} exception qualifies the original generalization.", r"Internal premodification still adds a cost (§\ref{sec:payne}). Peripheral NP modification can accommodate some determinative premodifiers, so it would overstate the difference to count every pre-head AdvP against the proposal. Internal cases such as \mention{the very few} nevertheless need a permission that ordinary common nouns lack. The attributive \mention{almost textbook} exception further qualifies the generalization.")
replace(r"\textcite{reynolds2026numerals} distinguishes determinative uses such as \mention{ten men}, proper-noun uses such as \mention{Room 101}, and common-noun uses such as \mention{tens of pens}.", r"\textcite{reynolds2026numerals} distinguishes determinative numerals such as \mention{ten} in \mention{ten men}, proper-noun cases such as \mention{10} in \mention{Room 10}, and common-noun numerals such as \mention{tens} in \mention{tens of pens}.")
replace(r"I retain \mention{who} as a pronoun and analyse interrogative and relative \mention{what} as determinative, with explicit interpretive restrictions.", r"The proposed treatment of \mention{what} and relative \mention{which} relocates a boundary within Noun.")

# Author's terminology preference in analytical prose, without touching sources or titles.
for old, new in [('reclassification','recategorization'), ('classification','categorization'), ('classifies','categorizes'), ('classify','categorize'), ('unclassified','uncategorized'), ('cross-categorization','cross-cutting features')]:
    s = s.replace(old, new).replace(old.capitalize(), new.capitalize())
replace(r'\mention{Apple} describes a class;', r'\mention{Apple} describes a category;')
replace('comparison class.', 'comparison group.')
assert not re.search(r'\b(?:classif\w*|reclassif\w*)\b', s, re.I)
p.write_text(s)
print('Revised manuscript:', len(s), 'characters')
